"use client";

import { Dispatch, SetStateAction } from "react";
import {
  startRegistration,
  type WebAuthnCredential,
} from "@simplewebauthn/browser";
import { getRegistrationOptions, verifyRegistration } from "../lib/registry";

interface RegisterPasskeyProps {
  setUserCredential: Dispatch<SetStateAction<WebAuthnCredential | null>>;
  setJwtPrivKey: Dispatch<SetStateAction<string | null>>;
  setJwtPubKey: Dispatch<SetStateAction<string | null>>;
}

function arrayBufferToPem(
  buffer: ArrayBuffer,
  type: "PUBLIC KEY" | "PRIVATE KEY"
): string {
  // Convert ArrayBuffer to base64
  const base64 = Buffer.from(buffer).toString("base64");

  // Split into 64-character lines (PEM standard)
  const lines = base64.match(/.{1,64}/g) || [];

  // Add PEM headers and footers
  return [`-----BEGIN ${type}-----`, ...lines, `-----END ${type}-----`].join(
    "\n"
  );
}

export default function RegisterPasskey({
  setUserCredential,
  setJwtPrivKey,
  setJwtPubKey,
}: RegisterPasskeyProps) {
  async function handleClick() {
    console.log("New passkey registration process started");

    const userName = `user_${Math.floor(Math.random() * 1000)}`;

    // Browser generates a public/private key pair for JWT signing
    const { publicKey, privateKey } = await window.crypto.subtle.generateKey(
      {
        name: "ECDSA",
        namedCurve: "P-256",
      },
      true,
      ["sign", "verify"]
    );

    const jwtPubKey = arrayBufferToPem(
      await window.crypto.subtle.exportKey("spki", publicKey),
      "PUBLIC KEY"
    );
    const jwtPrivKey = arrayBufferToPem(
      await window.crypto.subtle.exportKey("pkcs8", privateKey),
      "PRIVATE KEY"
    );

    console.log("JWT Public Key (passkey's userID):");
    console.log(jwtPubKey);
    console.log("JWT Private Key:");
    console.log(jwtPrivKey);

    console.log("Generating registration options...");
    const registrationOptions = await getRegistrationOptions(
      userName,
      jwtPubKey
    );
    console.log(
      "Registration options generated by server:",
      JSON.stringify(registrationOptions, null, 2)
    );

    console.log("Starting registration (authenticator interaction)...");
    const registrationResponse = await startRegistration({
      optionsJSON: registrationOptions,
    });
    console.log(
      "Registration response from authenticator:",
      JSON.stringify(registrationResponse, null, 2)
    );

    console.log("Verifying registration...");
    const verificationResponse = await verifyRegistration(
      userName,
      jwtPubKey,
      registrationResponse
    );
    console.log(
      "Verification response from server:",
      JSON.stringify(verificationResponse.verified, null, 2)
    );

    if (verificationResponse.registrationInfo) {
      setUserCredential(verificationResponse.registrationInfo.credential);
      setJwtPrivKey(jwtPrivKey);
      setJwtPubKey(jwtPubKey);
    } else {
      console.error(
        "Registration verification failed: no registration info found"
      );
    }
  }

  return (
    <button
      className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:w-auto"
      onClick={handleClick}
    >
      1. Registry new Passkey
    </button>
  );
}
